model:
  name_or_path: models/sft-lora-merged
  trust_remote_code: true
  attn_implementation: sdpa

quantization:
  load_in_4bit: true
  bnb_4bit_quant_type: nf4
  bnb_4bit_use_double_quant: true
  bnb_4bit_compute_dtype: float16

output_dir: models/sft-lora-merged-bnb4
